/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package orderingsystem;
import java.awt.CardLayout;
import javax.swing.*;
import java.util.*;
import java.io.*;
import java.text.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author eslemus
 */
public class mainMenu extends javax.swing.JFrame {
    double total;
    items Breakfast = new items();
    items Taco = new items();
    items Drink= new items();
    /**
     * Creates new form mainMenu
     */
    CardLayout cardLayout;
    
    public mainMenu() {
        initComponents();
        
        cardLayout = (CardLayout)(cardPanel.getLayout());
        
        drinksComboBox.setVisible(false);
        breakfastComboBox.setVisible(false);
        tacosComboBox.setVisible(false);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkoutPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        payBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        checkoutTextArea = new javax.swing.JTextArea();
        jSplitPane1 = new javax.swing.JSplitPane();
        leftPanel = new javax.swing.JPanel();
        breakfastLbl = new javax.swing.JLabel();
        tacosLbl = new javax.swing.JLabel();
        drinkLbl = new javax.swing.JLabel();
        breakfastComboBox = new javax.swing.JComboBox<>();
        tacosComboBox = new javax.swing.JComboBox<>();
        drinksComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cardPanel = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        breakfastPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        bStyle = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        bSecTop = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        bFirstTop = new javax.swing.JComboBox<>();
        breakfastItem = new javax.swing.JLabel();
        bfBtn = new javax.swing.JButton();
        tacosPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        tStyle = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        noOnion = new javax.swing.JCheckBox();
        noCilantro = new javax.swing.JCheckBox();
        noCheese = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        tacosBtn = new javax.swing.JButton();
        tacosItem = new javax.swing.JLabel();
        drinksPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        drinkItem = new javax.swing.JLabel();
        drinksBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        checkoutPanel.setPreferredSize(new java.awt.Dimension(344, 500));

        jLabel4.setText("Review Order");

        payBtn.setText("Pay Order");
        payBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payBtnActionPerformed(evt);
            }
        });

        checkoutTextArea.setEditable(false);
        checkoutTextArea.setColumns(20);
        checkoutTextArea.setRows(5);
        jScrollPane1.setViewportView(checkoutTextArea);

        javax.swing.GroupLayout checkoutPanelLayout = new javax.swing.GroupLayout(checkoutPanel);
        checkoutPanel.setLayout(checkoutPanelLayout);
        checkoutPanelLayout.setHorizontalGroup(
            checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkoutPanelLayout.createSequentialGroup()
                .addGroup(checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkoutPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE))
                    .addGroup(checkoutPanelLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(payBtn)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(checkoutPanelLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jLabel4)
                .addContainerGap(153, Short.MAX_VALUE))
        );
        checkoutPanelLayout.setVerticalGroup(
            checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkoutPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                .addGap(15, 15, 15)
                .addComponent(payBtn)
                .addContainerGap())
        );

        jSplitPane1.setPreferredSize(new java.awt.Dimension(850, 500));

        leftPanel.setBackground(new java.awt.Color(153, 204, 255));
        leftPanel.setPreferredSize(new java.awt.Dimension(200, 500));

        breakfastLbl.setText("Breakfast");
        breakfastLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                breakfastLblMouseClicked(evt);
            }
        });

        tacosLbl.setText("Tacos");
        tacosLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tacosLblMouseClicked(evt);
            }
        });

        drinkLbl.setText("Drinks");
        drinkLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                drinkLblMouseClicked(evt);
            }
        });

        breakfastComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Breakfast Burrito", "Breakfast Taco" }));
        breakfastComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                breakfastComboBoxActionPerformed(evt);
            }
        });

        tacosComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grilled Beef", "Grilled Chicken", "Pastor", "Barbacoa" }));
        tacosComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tacosComboBoxActionPerformed(evt);
            }
        });

        drinksComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Horchata", "Jamaica", "Sprite", "Coca-Cola" }));
        drinksComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drinksComboBoxActionPerformed(evt);
            }
        });

        jLabel2.setText("****insert logo");

        jLabel1.setText("Dia de los Tacos");

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftPanelLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tacosLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tacosComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(breakfastComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(drinksComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(breakfastLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(drinkLbl))
                .addGap(17, 17, 17))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addGap(58, 58, 58)
                .addComponent(breakfastLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(breakfastComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(tacosLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tacosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(drinkLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(drinksComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(leftPanel);

        cardPanel.setBackground(new java.awt.Color(204, 255, 204));
        cardPanel.setLayout(new java.awt.CardLayout());

        jLabel10.setText("home screen first panel, add temporary background");

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                .addContainerGap(163, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(148, 148, 148))
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabel10)
                .addContainerGap(290, Short.MAX_VALUE))
        );

        cardPanel.add(homePanel, "homePanel");

        breakfastPanel.setBackground(new java.awt.Color(204, 204, 255));

        jLabel7.setText("Tortilla Style:");

        bStyle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Flour", "Spinach", "Corn" }));

        jLabel5.setText("First topping: ");

        bSecTop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bacon", "Black beans", "Refried beans", "Chorizo", "Jalapeño", "Potato", "Vegan Chorizo", "Grilled Onions" }));

        jLabel6.setText("Second Topping:");

        bFirstTop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bacon", "Black beans", "Refried beans", "Chorizo", "Jalapeño", "Potato", "Vegan Chorizo", "Grilled Onions", " ", " " }));

        breakfastItem.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 2, true));

        bfBtn.setText("Add to Cart");
        bfBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bfBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout breakfastPanelLayout = new javax.swing.GroupLayout(breakfastPanel);
        breakfastPanel.setLayout(breakfastPanelLayout);
        breakfastPanelLayout.setHorizontalGroup(
            breakfastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, breakfastPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bfBtn)
                .addGap(189, 189, 189))
            .addGroup(breakfastPanelLayout.createSequentialGroup()
                .addGroup(breakfastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(breakfastPanelLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bStyle, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(breakfastPanelLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(breakfastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bSecTop, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(122, 122, 122)
                        .addGroup(breakfastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(bFirstTop, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(breakfastPanelLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(breakfastItem, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(218, Short.MAX_VALUE))
        );
        breakfastPanelLayout.setVerticalGroup(
            breakfastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(breakfastPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(breakfastItem, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addGroup(breakfastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(bStyle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(110, 110, 110)
                .addGroup(breakfastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(breakfastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSecTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bFirstTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(bfBtn)
                .addGap(61, 61, 61))
        );

        cardPanel.add(breakfastPanel, "breakfastPanel");

        tacosPanel.setBackground(new java.awt.Color(204, 255, 204));
        tacosPanel.setPreferredSize(new java.awt.Dimension(637, 500));

        jLabel8.setText("Tortilla Style:");

        tStyle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Flour", "Spinach", "Corn" }));

        jLabel9.setText("Pick it off:");

        noOnion.setText("No Onion");

        noCilantro.setText("No Cilantro");

        noCheese.setText("No Cojita Cheese");

        jLabel12.setText("Tacos");

        tacosBtn.setText("Add to Cart");
        tacosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tacosBtnActionPerformed(evt);
            }
        });

        tacosItem.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 255, 204), 2, true));

        javax.swing.GroupLayout tacosPanelLayout = new javax.swing.GroupLayout(tacosPanel);
        tacosPanel.setLayout(tacosPanelLayout);
        tacosPanelLayout.setHorizontalGroup(
            tacosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tacosPanelLayout.createSequentialGroup()
                .addGroup(tacosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tacosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(tacosPanelLayout.createSequentialGroup()
                            .addGap(109, 109, 109)
                            .addGroup(tacosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(tacosBtn)
                                .addGroup(tacosPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(18, 18, 18)
                                    .addComponent(tStyle, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(106, 106, 106))))
                        .addGroup(tacosPanelLayout.createSequentialGroup()
                            .addGap(148, 148, 148)
                            .addComponent(jLabel9))
                        .addGroup(tacosPanelLayout.createSequentialGroup()
                            .addGap(216, 216, 216)
                            .addComponent(noOnion))
                        .addGroup(tacosPanelLayout.createSequentialGroup()
                            .addGap(190, 190, 190)
                            .addComponent(noCheese)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(noCilantro)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tacosPanelLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(tacosItem, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel12)))
                .addContainerGap(197, Short.MAX_VALUE))
        );
        tacosPanelLayout.setVerticalGroup(
            tacosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tacosPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(tacosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(tacosItem, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(tacosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tStyle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(84, 84, 84)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tacosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noCilantro)
                    .addComponent(noCheese))
                .addGap(18, 18, 18)
                .addComponent(noOnion)
                .addGap(59, 59, 59)
                .addComponent(tacosBtn)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        cardPanel.add(tacosPanel, "tacosPanel");

        drinksPanel.setBackground(new java.awt.Color(255, 204, 204));

        jLabel11.setText("Drink:");

        drinkItem.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));

        drinksBtn.setText("Add to Cart");
        drinksBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drinksBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout drinksPanelLayout = new javax.swing.GroupLayout(drinksPanel);
        drinksPanel.setLayout(drinksPanelLayout);
        drinksPanelLayout.setHorizontalGroup(
            drinksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(drinksPanelLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(drinksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(drinksBtn)
                    .addComponent(drinkItem, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(294, Short.MAX_VALUE))
        );
        drinksPanelLayout.setVerticalGroup(
            drinksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(drinksPanelLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(drinksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(drinkItem, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(66, 66, 66)
                .addComponent(drinksBtn)
                .addContainerGap(263, Short.MAX_VALUE))
        );

        cardPanel.add(drinksPanel, "drinksPanel");

        jSplitPane1.setRightComponent(cardPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(checkoutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkoutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void drinkLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drinkLblMouseClicked
        // Visibility of menu items, double-click: hides combobox
        if (drinksComboBox.isVisible())
        {
            drinksComboBox.setVisible(false);
            cardLayout.show(cardPanel, "homePanel");
        }
        else if(breakfastComboBox.isVisible() || tacosComboBox.isVisible())
        {
          drinksComboBox.setVisible(true); 
          breakfastComboBox.setVisible(false);
          tacosComboBox.setVisible(false);
          cardLayout.show(cardPanel, "homePanel");
        }
        else
            drinksComboBox.setVisible(true);
    }//GEN-LAST:event_drinkLblMouseClicked

    private void drinksComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drinksComboBoxActionPerformed

        cardLayout.show(cardPanel, "drinksPanel");
        
        if(drinksComboBox.getSelectedItem() == "Horchata")
        {
            drinkItem.setText("Horchata");
             
             Drink.setName("Horchata");
             Drink.setPrice(3.5);
             total= total+Drink.getPrice();
             
             
        }
        else if(drinksComboBox.getSelectedItem() == "Jamaica")
        {
            drinkItem.setText("Jamaica");
            
            Drink.setName("Jamaica");
            Drink.setPrice(3.25);
            total = total + Drink.getPrice();
        }
        else if(drinksComboBox.getSelectedItem() == "Sprite")
        {
            drinkItem.setText("Sprite");
            
            
            Drink.setName("Sprite");
            Drink.setPrice(2.75);
            total=total+ Drink.getPrice();
        }
        else if(drinksComboBox.getSelectedItem() == "Coca-Cola")
        {
            drinkItem.setText("Coca-Cola");
     
           
            Drink.setName("Cola");
            Drink.setPrice(2.75);
             total=total+ Drink.getPrice();
        }
        
    }//GEN-LAST:event_drinksComboBoxActionPerformed

    private void breakfastLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_breakfastLblMouseClicked
        
        //when it's clicked
        if (breakfastComboBox.isVisible())
        {
            breakfastComboBox.setVisible(false); //hides menu items
            cardLayout.show(cardPanel, "homePanel"); //hides breakfast panel
        }
        else if(drinksComboBox.isVisible() || tacosComboBox.isVisible())
        { 
            //sets breakfast menu items ONLY visible
          drinksComboBox.setVisible(false); 
          breakfastComboBox.setVisible(true); 
          tacosComboBox.setVisible(false);
          cardLayout.show(cardPanel, "homePanel");
        }
        else
            breakfastComboBox.setVisible(true); //toggle between menu type and item
    }//GEN-LAST:event_breakfastLblMouseClicked

    private void tacosLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tacosLblMouseClicked
        // TODO addyour handling code here:
        if (tacosComboBox.isVisible())
        {
            tacosComboBox.setVisible(false);
            cardLayout.show(cardPanel, "homePanel");
        }
        else if(drinksComboBox.isVisible() || breakfastComboBox.isVisible())
        {
          drinksComboBox.setVisible(false); 
          breakfastComboBox.setVisible(false);
          tacosComboBox.setVisible(true);
          cardLayout.show(cardPanel, "homePanel");
        }
        else
            tacosComboBox.setVisible(true);  
    }//GEN-LAST:event_tacosLblMouseClicked

    private void tacosComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tacosComboBoxActionPerformed
        cardLayout.show(cardPanel, "tacosPanel");
        
        if(tacosComboBox.getSelectedItem() == "Grilled Beef")
        {
            tacosItem.setText("Grilled Beef");
            Taco.setName("Grilled Beef Taco");
            Taco.setPrice(2.75);
            total=total+Taco.getPrice();
        }
        else if(tacosComboBox.getSelectedItem() == "Grilled Chicken")
        {
            tacosItem.setText("Grilled Chicken");
             Taco.setName("Grilled chicken Taco");
            Taco.setPrice(2.5);
            total=total+Taco.getPrice();
        }
        else if(tacosComboBox.getSelectedItem() == "Pastor")
        {
            tacosItem.setText("Pastor");
            Taco.setName("Pastor Taco");
            Taco.setPrice(2.25);
            total=total+Taco.getPrice();
        }
        else if(tacosComboBox.getSelectedItem() == "Barbacoa")
        {
            tacosItem.setText("Barbacoa");
            Taco.setName("Barbacoa Taco");
            Taco.setPrice(2.5);
            total=total+Taco.getPrice();
        }
    }//GEN-LAST:event_tacosComboBoxActionPerformed

    private void payBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payBtnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_payBtnActionPerformed

    private void bfBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bfBtnActionPerformed
                //BREAKFAST: writes to Review Order Panel
        String type = breakfastItem.getText();
        String style = bStyle.getSelectedItem().toString();
        String firstTop = bFirstTop.getSelectedItem().toString();
        String secTop = bSecTop.getSelectedItem().toString();

        //the following resets the window
        drinksComboBox.setVisible(false);
        breakfastComboBox.setVisible(false);
        tacosComboBox.setVisible(false);
        cardLayout.show(cardPanel, "homePanel"); //hides any of the 3 types of panel

        checkoutTextArea.append(type);
        checkoutTextArea.append("\n   > Tortilla Style: " + style +
            "\n   > First Topping: " + firstTop + "\n   > Second Topping: " + secTop + "\n");
        checkoutTextArea.append("The total is: "+ total + "\n");

    }//GEN-LAST:event_bfBtnActionPerformed

    private void breakfastComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_breakfastComboBoxActionPerformed
        
        cardLayout.show(cardPanel, "breakfastPanel");
        
        if(breakfastComboBox.getSelectedItem() == "Breakfast Burrito")
        {
            breakfastItem.setText("Breakfast Burrito");
            Breakfast.setName("Breakfast Burrito");
            Breakfast.setPrice(5.25);
            total= total+ Breakfast.getPrice();
            
        }
        else if(breakfastComboBox.getSelectedItem() == "Breakfast Taco")
        {
            breakfastItem.setText("Breakfast Taco");
            Breakfast.setName("Breakfast Taco");
            Breakfast.setPrice(4.75);
            total= total+ Breakfast.getPrice();
        }
    }//GEN-LAST:event_breakfastComboBoxActionPerformed

    private void tacosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tacosBtnActionPerformed
        //TACOS: writes to Review Order Panel
        
        String type = tacosItem.getText();
        String editStyle = tStyle.getSelectedItem().toString();
        
        //-------THIS STILL NEEDS WORK-------------------------
        List<String> toppings = new ArrayList<String>(); 
        if(noCheese.isSelected())
            toppings.add(" Cheese ");
        else if(noCilantro.isSelected())
            toppings.add(" Cilantro ");
        else if(noOnion.isSelected())
            toppings.add(" Onions ");
        //-------------------------------------------------------
        
        //appends to text area
        checkoutTextArea.append(type + " Tacos \n");         
        checkoutTextArea.append("  > Tortilla Style: "+ editStyle +
            "\n   > Pick it off:" + toppings + "\n");
        checkoutTextArea.append("The total is: "+ total + "\n");

        //the following resets the window
        drinksComboBox.setVisible(false);
        breakfastComboBox.setVisible(false);
        tacosComboBox.setVisible(false);
        
        
        
        cardLayout.show(cardPanel, "homePanel"); //hides any of the 3 types of panel
        
    }//GEN-LAST:event_tacosBtnActionPerformed

    private void drinksBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drinksBtnActionPerformed
        //TACOS: writes to Review Order Panel
       
        String text =  drinkItem.getText();

        //the following resets the window
        drinksComboBox.setVisible(false);
        breakfastComboBox.setVisible(false);
        tacosComboBox.setVisible(false);
        cardLayout.show(cardPanel, "homePanel"); //hides any of the 3 types of panel

        checkoutTextArea.append("Drink: ");
        checkoutTextArea.append(Drink.getName()+ "\n");
        
        checkoutTextArea.append("The total is: "+ total+ "\n");
        
        
    }//GEN-LAST:event_drinksBtnActionPerformed

      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> bFirstTop;
    private javax.swing.JComboBox<String> bSecTop;
    private javax.swing.JComboBox<String> bStyle;
    private javax.swing.JButton bfBtn;
    private javax.swing.JComboBox<String> breakfastComboBox;
    private javax.swing.JLabel breakfastItem;
    private javax.swing.JLabel breakfastLbl;
    private javax.swing.JPanel breakfastPanel;
    private javax.swing.JPanel cardPanel;
    private javax.swing.JPanel checkoutPanel;
    private javax.swing.JTextArea checkoutTextArea;
    private javax.swing.JLabel drinkItem;
    private javax.swing.JLabel drinkLbl;
    private javax.swing.JButton drinksBtn;
    public javax.swing.JComboBox<String> drinksComboBox;
    private javax.swing.JPanel drinksPanel;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JCheckBox noCheese;
    private javax.swing.JCheckBox noCilantro;
    private javax.swing.JCheckBox noOnion;
    private javax.swing.JButton payBtn;
    private javax.swing.JComboBox<String> tStyle;
    private javax.swing.JButton tacosBtn;
    private javax.swing.JComboBox<String> tacosComboBox;
    private javax.swing.JLabel tacosItem;
    private javax.swing.JLabel tacosLbl;
    private javax.swing.JPanel tacosPanel;
    // End of variables declaration//GEN-END:variables
}
