/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package orderingsystem;
import java.awt.CardLayout;
import java.util.*;
import java.io.*;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author eslemus
 */
public class mainMenu extends javax.swing.JFrame {
    double subtotal;
    DecimalFormat formatter;
    
    //instantiation of classes
    items Breakfast = new items();
    items Taco = new items();
    items Drink= new items();
    Billing bill = new Billing();
    
    /**
     * Creates new form mainMenu
     */
    CardLayout cardLayout;
    
    public mainMenu() {
        initComponents();
        
        formatter = new DecimalFormat("#,###.00");
        
        //custom layout for panels
        cardLayout = (CardLayout)(cardPanel.getLayout());
        
        drinksComboBox.setVisible(false);
        breakfastComboBox.setVisible(false);
        tacosComboBox.setVisible(false);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkoutPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        payBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        checkoutTextArea = new javax.swing.JTextArea();
        runSubtotal = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        leftPanel = new javax.swing.JPanel();
        breakfastLbl = new javax.swing.JLabel();
        tacosLbl = new javax.swing.JLabel();
        drinkLbl = new javax.swing.JLabel();
        breakfastComboBox = new javax.swing.JComboBox<>();
        tacosComboBox = new javax.swing.JComboBox<>();
        drinksComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cardPanel = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        breakfastPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        bStyle = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        bSecTop = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        bFirstTop = new javax.swing.JComboBox<>();
        breakfastItem = new javax.swing.JLabel();
        bfBtn = new javax.swing.JButton();
        tacosPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        tStyle = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        noTopping3 = new javax.swing.JCheckBox();
        noTopping2 = new javax.swing.JCheckBox();
        noTopping1 = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        tacosBtn = new javax.swing.JButton();
        tacosItem = new javax.swing.JLabel();
        drinksPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        drinkItem = new javax.swing.JLabel();
        drinksBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        checkoutPanel.setBackground(new java.awt.Color(51, 51, 51));
        checkoutPanel.setPreferredSize(new java.awt.Dimension(344, 500));

        jLabel4.setFont(new java.awt.Font("Phosphate", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 153));
        jLabel4.setText("Review Order");

        payBtn.setBackground(new java.awt.Color(51, 51, 51));
        payBtn.setFont(new java.awt.Font("American Typewriter", 1, 14)); // NOI18N
        payBtn.setForeground(new java.awt.Color(255, 153, 51));
        payBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/orderingsystem/output_order.png"))); // NOI18N
        payBtn.setText("Send");
        payBtn.setAlignmentY(0.0F);
        payBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payBtnActionPerformed(evt);
            }
        });

        checkoutTextArea.setEditable(false);
        checkoutTextArea.setColumns(20);
        checkoutTextArea.setRows(5);
        checkoutTextArea.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 1, 1, 3, new java.awt.Color(255, 153, 51)));
        jScrollPane1.setViewportView(checkoutTextArea);

        runSubtotal.setBackground(new java.awt.Color(204, 255, 204));
        runSubtotal.setFont(new java.awt.Font("American Typewriter", 0, 12)); // NOI18N
        runSubtotal.setForeground(new java.awt.Color(255, 255, 102));

        javax.swing.GroupLayout checkoutPanelLayout = new javax.swing.GroupLayout(checkoutPanel);
        checkoutPanel.setLayout(checkoutPanelLayout);
        checkoutPanelLayout.setHorizontalGroup(
            checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkoutPanelLayout.createSequentialGroup()
                .addGroup(checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(checkoutPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(runSubtotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(payBtn)
                        .addGap(4, 4, 4))
                    .addGroup(checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(checkoutPanelLayout.createSequentialGroup()
                            .addGap(72, 72, 72)
                            .addComponent(jLabel4))
                        .addGroup(checkoutPanelLayout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        checkoutPanelLayout.setVerticalGroup(
            checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkoutPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(checkoutPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(payBtn))
                    .addGroup(checkoutPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(runSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane1.setPreferredSize(new java.awt.Dimension(850, 500));

        leftPanel.setBackground(new java.awt.Color(51, 51, 51));
        leftPanel.setPreferredSize(new java.awt.Dimension(200, 500));

        breakfastLbl.setBackground(new java.awt.Color(204, 204, 204));
        breakfastLbl.setFont(new java.awt.Font("Phosphate", 0, 18)); // NOI18N
        breakfastLbl.setForeground(new java.awt.Color(153, 255, 153));
        breakfastLbl.setText("Breakfast");
        breakfastLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                breakfastLblMouseClicked(evt);
            }
        });

        tacosLbl.setFont(new java.awt.Font("Phosphate", 0, 18)); // NOI18N
        tacosLbl.setForeground(new java.awt.Color(190, 13, 241));
        tacosLbl.setText("Tacos");
        tacosLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tacosLblMouseClicked(evt);
            }
        });

        drinkLbl.setFont(new java.awt.Font("Phosphate", 0, 18)); // NOI18N
        drinkLbl.setForeground(new java.awt.Color(153, 255, 153));
        drinkLbl.setText("Drinks");
        drinkLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                drinkLblMouseClicked(evt);
            }
        });

        breakfastComboBox.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        breakfastComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Breakfast Burrito", "Breakfast Taco" }));
        breakfastComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                breakfastComboBoxActionPerformed(evt);
            }
        });

        tacosComboBox.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        tacosComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grilled Beef", "Grilled Chicken", "Pastor", "Barbacoa" }));
        tacosComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tacosComboBoxActionPerformed(evt);
            }
        });

        drinksComboBox.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        drinksComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Horchata", "Jamaica", "Sprite", "Coca-Cola" }));
        drinksComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drinksComboBoxActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/orderingsystem/tacos_logo.png"))); // NOI18N

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tacosLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tacosComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(breakfastComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(drinksComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(breakfastLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(drinkLbl))
                .addGap(17, 17, 17))
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(breakfastLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(breakfastComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(tacosLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tacosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(drinkLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(drinksComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(leftPanel);

        cardPanel.setBackground(new java.awt.Color(204, 255, 204));
        cardPanel.setLayout(new java.awt.CardLayout());

        homePanel.setBackground(new java.awt.Color(51, 51, 51));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/orderingsystem/homePanel.jpeg"))); // NOI18N

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 496, Short.MAX_VALUE)
        );

        cardPanel.add(homePanel, "homePanel");

        breakfastPanel.setBackground(new java.awt.Color(0, 0, 0));

        jLabel7.setFont(new java.awt.Font("American Typewriter", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(191, 21, 233));
        jLabel7.setText("Tortilla Style:");

        bStyle.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        bStyle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Flour", "Spinach", "Corn" }));

        jLabel5.setFont(new java.awt.Font("American Typewriter", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(191, 21, 233));
        jLabel5.setText("First topping: ");

        bSecTop.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        bSecTop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bacon", "Black beans", "Refried beans", "Chorizo", "Jalapeño", "Potato", "Vegan Chorizo", "Grilled Onions" }));

        jLabel6.setFont(new java.awt.Font("American Typewriter", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(191, 21, 233));
        jLabel6.setText("Second Topping:");

        bFirstTop.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        bFirstTop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bacon", "Black beans", "Refried beans", "Chorizo", "Jalapeño", "Potato", "Vegan Chorizo", "Grilled Onions", " ", " " }));

        breakfastItem.setFont(new java.awt.Font("Phosphate", 0, 14)); // NOI18N
        breakfastItem.setForeground(new java.awt.Color(153, 255, 153));
        breakfastItem.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(191, 21, 233), 2, true));

        bfBtn.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        bfBtn.setForeground(new java.awt.Color(32, 233, 110));
        bfBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/orderingsystem/add_to_cart.png"))); // NOI18N
        bfBtn.setText("Add to Cart");
        bfBtn.setToolTipText("");
        bfBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bfBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bfBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout breakfastPanelLayout = new javax.swing.GroupLayout(breakfastPanel);
        breakfastPanel.setLayout(breakfastPanelLayout);
        breakfastPanelLayout.setHorizontalGroup(
            breakfastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(breakfastPanelLayout.createSequentialGroup()
                .addGroup(breakfastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(breakfastPanelLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(breakfastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(breakfastPanelLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, breakfastPanelLayout.createSequentialGroup()
                                .addComponent(bSecTop, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bFirstTop, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10))))
                    .addGroup(breakfastPanelLayout.createSequentialGroup()
                        .addGroup(breakfastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(breakfastPanelLayout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(breakfastItem, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(breakfastPanelLayout.createSequentialGroup()
                                .addGap(155, 155, 155)
                                .addComponent(jLabel7)
                                .addGap(35, 35, 35)
                                .addComponent(bStyle, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 66, Short.MAX_VALUE)))
                .addGap(132, 132, 132))
            .addGroup(breakfastPanelLayout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(bfBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        breakfastPanelLayout.setVerticalGroup(
            breakfastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(breakfastPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(breakfastItem, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addGroup(breakfastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(bStyle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(breakfastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(breakfastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSecTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bFirstTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(bfBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        cardPanel.add(breakfastPanel, "breakfastPanel");

        tacosPanel.setBackground(new java.awt.Color(0, 0, 0));
        tacosPanel.setPreferredSize(new java.awt.Dimension(637, 500));

        jLabel8.setFont(new java.awt.Font("American Typewriter", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(191, 21, 233));
        jLabel8.setText("Tortilla Style:");

        tStyle.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        tStyle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Flour", "Spinach", "Corn" }));

        jLabel9.setFont(new java.awt.Font("American Typewriter", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(191, 21, 233));
        jLabel9.setText("Pick it off:");

        noTopping3.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        noTopping3.setForeground(new java.awt.Color(255, 255, 153));
        noTopping3.setText("No Onion");

        noTopping2.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        noTopping2.setForeground(new java.awt.Color(255, 255, 153));
        noTopping2.setText("No Cilantro");

        noTopping1.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        noTopping1.setForeground(new java.awt.Color(255, 255, 153));
        noTopping1.setText("No Cojita Cheese");

        jLabel12.setFont(new java.awt.Font("American Typewriter", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 153));
        jLabel12.setText("Tacos");

        tacosBtn.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        tacosBtn.setForeground(new java.awt.Color(191, 21, 233));
        tacosBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/orderingsystem/add_to_cart.png"))); // NOI18N
        tacosBtn.setText("Add to Cart");
        tacosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tacosBtnActionPerformed(evt);
            }
        });

        tacosItem.setFont(new java.awt.Font("Phosphate", 0, 18)); // NOI18N
        tacosItem.setForeground(new java.awt.Color(255, 255, 153));
        tacosItem.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(191, 21, 233), 2, true));

        javax.swing.GroupLayout tacosPanelLayout = new javax.swing.GroupLayout(tacosPanel);
        tacosPanel.setLayout(tacosPanelLayout);
        tacosPanelLayout.setHorizontalGroup(
            tacosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tacosPanelLayout.createSequentialGroup()
                .addGroup(tacosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tacosPanelLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(tacosItem, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tacosPanelLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(tacosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tacosPanelLayout.createSequentialGroup()
                                .addGroup(tacosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8))
                                .addGap(31, 31, 31)
                                .addComponent(tStyle, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tacosPanelLayout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addGroup(tacosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(noTopping2)
                                    .addComponent(noTopping1)
                                    .addComponent(noTopping3))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(tacosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(tacosBtn))
                .addGap(37, 37, 37))
        );
        tacosPanelLayout.setVerticalGroup(
            tacosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tacosPanelLayout.createSequentialGroup()
                .addGroup(tacosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tacosPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(tacosItem, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tacosPanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel12)))
                .addGap(66, 66, 66)
                .addGroup(tacosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tStyle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addComponent(jLabel9)
                .addGap(1, 1, 1)
                .addComponent(noTopping1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(noTopping2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(noTopping3)
                .addGap(30, 30, 30)
                .addComponent(tacosBtn)
                .addGap(27, 27, 27))
        );

        cardPanel.add(tacosPanel, "tacosPanel");

        drinksPanel.setBackground(new java.awt.Color(0, 0, 0));

        jLabel11.setFont(new java.awt.Font("Phosphate", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(191, 21, 233));
        jLabel11.setText("Drink:");

        drinkItem.setFont(new java.awt.Font("American Typewriter", 0, 12)); // NOI18N
        drinkItem.setForeground(new java.awt.Color(255, 255, 153));
        drinkItem.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));

        drinksBtn.setFont(new java.awt.Font("American Typewriter", 0, 12)); // NOI18N
        drinksBtn.setForeground(new java.awt.Color(191, 21, 233));
        drinksBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/orderingsystem/add_to_cart.png"))); // NOI18N
        drinksBtn.setText("Add to Cart");
        drinksBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drinksBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout drinksPanelLayout = new javax.swing.GroupLayout(drinksPanel);
        drinksPanel.setLayout(drinksPanelLayout);
        drinksPanelLayout.setHorizontalGroup(
            drinksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(drinksPanelLayout.createSequentialGroup()
                .addGroup(drinksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(drinksPanelLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(drinkItem, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(drinksPanelLayout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(drinksBtn)))
                .addContainerGap(218, Short.MAX_VALUE))
        );
        drinksPanelLayout.setVerticalGroup(
            drinksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(drinksPanelLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(drinksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(drinkItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(104, 104, 104)
                .addComponent(drinksBtn)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        cardPanel.add(drinksPanel, "drinksPanel");

        jSplitPane1.setRightComponent(cardPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkoutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(checkoutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//-----------------breakfast functionality--------------------------------------
    /**************************************************************************
     Purpose: toggles between Menu Type, Menu Item and it's panel, 
              where type is the label and item is within the combo box
        Returns: None *********************************************************/
    private void breakfastLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_breakfastLblMouseClicked
        
        //when it's clicked
        if (breakfastComboBox.isVisible())
        {
            breakfastComboBox.setVisible(false); //hides menu items
            cardLayout.show(cardPanel, "homePanel"); //hides breakfast panel
        }
        else if(drinksComboBox.isVisible() || tacosComboBox.isVisible())
        { 
            //sets breakfast menu items ONLY visible
          drinksComboBox.setVisible(false); 
          breakfastComboBox.setVisible(true); 
          tacosComboBox.setVisible(false);
          cardLayout.show(cardPanel, "homePanel");
        }
        else
            breakfastComboBox.setVisible(true); 
    }//GEN-LAST:event_breakfastLblMouseClicked
    
    /**************************************************************************
        Purpose: [Add to Cart Button] writes to Review Order Panel, while
                resetting the window
        Returns: None *********************************************************/     
    private void bfBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bfBtnActionPerformed
                //BREAKFAST: writes to Review Order Panel
        String type = breakfastItem.getText();
        String style = bStyle.getSelectedItem().toString();
        String firstTop = bFirstTop.getSelectedItem().toString();
        String secTop = bSecTop.getSelectedItem().toString();

        //the following resets the window
        drinksComboBox.setVisible(false);
        breakfastComboBox.setVisible(false);
        tacosComboBox.setVisible(false);
        cardLayout.show(cardPanel, "homePanel"); //hides any of the 3 types of panel

        checkoutTextArea.append("\n" + type);
        checkoutTextArea.append("\n   > Tortilla Style: " + style +
            "\n   > First Topping: " + firstTop + "\n   > Second Topping: " + secTop + "\n");
        
        runSubtotal.setText("Subtotal: \n $" + formatter.format(subtotal)); //label with running subtotal
        
    }//GEN-LAST:event_bfBtnActionPerformed
    
    /**************************************************************************
        Purpose: Displays breakfast panel when user chooses a menu item
               Initializes setters from items class, Updates subtotal variable
        Returns: None *********************************************************/ 
    private void breakfastComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_breakfastComboBoxActionPerformed
        
        cardLayout.show(cardPanel, "breakfastPanel");
        
        if(breakfastComboBox.getSelectedItem() == "Breakfast Burrito")
        {
            breakfastItem.setText("Breakfast Burrito");
            Breakfast.setName("Breakfast Burrito");
            Breakfast.setPrice(7.50);
            subtotal= subtotal+ Breakfast.getPrice();
            
        }
        else if(breakfastComboBox.getSelectedItem() == "Breakfast Taco")
        {
            breakfastItem.setText("Breakfast Taco");
            Breakfast.setName("Breakfast Taco");
            Breakfast.setPrice(2.50);
            subtotal= subtotal+ Breakfast.getPrice();
        }
    }//GEN-LAST:event_breakfastComboBoxActionPerformed
 //-----------------------------------------------------------------------------
    
//---------------------drinks functionality-------------------------------------
    
    /**************************************************************************
        Purpose: [Add to Cart Button] writes to Review Order Panel, while
                resetting the window
        Returns: None *********************************************************/ 
    private void drinksBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drinksBtnActionPerformed
        //TACOS: writes to Review Order Panel
       
        String text =  drinkItem.getText();

        //the following resets the window
        drinksComboBox.setVisible(false);
        breakfastComboBox.setVisible(false);
        tacosComboBox.setVisible(false);
        cardLayout.show(cardPanel, "homePanel"); //hides any of the 3 types of panel

        checkoutTextArea.append("\n Drink: ");
        checkoutTextArea.append(Drink.getName()+ "\n");
        
        runSubtotal.setText("Subtotal: \n $" + formatter.format(subtotal)); //label with running subtotal
        
        
    }//GEN-LAST:event_drinksBtnActionPerformed

    /**************************************************************************
        Purpose: Displays drinks panel when user chooses a menu item
               Initializes setters from items class, Updates subtotal variable
        Returns: None *********************************************************/
    private void drinksComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drinksComboBoxActionPerformed
        
        cardLayout.show(cardPanel, "drinksPanel");
        
        if(drinksComboBox.getSelectedItem() == "Horchata")
        {
            drinkItem.setText("Horchata");
             
             Drink.setName("Horchata");
             Drink.setPrice(3.25);
             subtotal= subtotal+Drink.getPrice();
        }
        else if(drinksComboBox.getSelectedItem() == "Jamaica")
        {
            drinkItem.setText("Jamaica");
            
            Drink.setName("Jamaica");
            Drink.setPrice(3.25);
            subtotal = subtotal + Drink.getPrice();
        }
        else if(drinksComboBox.getSelectedItem() == "Sprite")
        {
            drinkItem.setText("Sprite");
            
            
            Drink.setName("Sprite");
            Drink.setPrice(2.75);
            subtotal=subtotal+ Drink.getPrice();
        }
        else if(drinksComboBox.getSelectedItem() == "Coca-Cola")
        {
            drinkItem.setText("Coca-Cola");
     
           
            Drink.setName("Cola");
            Drink.setPrice(2.75);
             subtotal=subtotal+ Drink.getPrice();
        }
    }//GEN-LAST:event_drinksComboBoxActionPerformed

    /**************************************************************************
     Purpose: toggles between Menu Type, Menu Item and it's panel, 
              where type is the label and item is within the combo box
        Returns: None *********************************************************/
    private void drinkLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drinkLblMouseClicked
        
        if (drinksComboBox.isVisible())
        {
            drinksComboBox.setVisible(false);
            cardLayout.show(cardPanel, "homePanel");
        }
        else if(breakfastComboBox.isVisible() || tacosComboBox.isVisible())
        {
          drinksComboBox.setVisible(true); 
          breakfastComboBox.setVisible(false);
          tacosComboBox.setVisible(false);
          cardLayout.show(cardPanel, "homePanel");
        }
        else
            drinksComboBox.setVisible(true);
    }//GEN-LAST:event_drinkLblMouseClicked

//----------------tacos functionality-------------------------------------------
    
    /**************************************************************************
     Purpose: toggles between Menu Type, Menu Item and it's panel, 
              where type is the label and item is within the combo box
        Returns: None *********************************************************/
    private void tacosLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tacosLblMouseClicked
        if (tacosComboBox.isVisible())
        {
            tacosComboBox.setVisible(false);
            cardLayout.show(cardPanel, "homePanel");
        }
        else if(drinksComboBox.isVisible() || breakfastComboBox.isVisible())
        {
          drinksComboBox.setVisible(false); 
          breakfastComboBox.setVisible(false);
          tacosComboBox.setVisible(true);
          cardLayout.show(cardPanel, "homePanel");
        }
        else
            tacosComboBox.setVisible(true);  
    }//GEN-LAST:event_tacosLblMouseClicked

    /**************************************************************************
        Purpose: Displays tacos panel when user chooses a menu item
               Initializes setters from items class, Updates subtotal variable
        Returns: None *********************************************************/
    private void tacosComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tacosComboBoxActionPerformed
     
        cardLayout.show(cardPanel, "tacosPanel");
        
           
        if(tacosComboBox.getSelectedItem() == "Grilled Beef")
        {
            tacosItem.setText("Grilled Beef");
            Taco.setName("Grilled Beef Taco");
            Taco.setPrice(2.75);
            subtotal=subtotal+Taco.getPrice();
        }
        else if(tacosComboBox.getSelectedItem() == "Grilled Chicken")
        {
            tacosItem.setText("Grilled Chicken");
             Taco.setName("Grilled chicken Taco");
            Taco.setPrice(2.5);
            subtotal=subtotal+Taco.getPrice();
        }
        else if(tacosComboBox.getSelectedItem() == "Pastor")
        {
            tacosItem.setText("Pastor");
            Taco.setName("Pastor Taco");
            Taco.setPrice(2.25);
            subtotal=subtotal+Taco.getPrice();
        }
        else if(tacosComboBox.getSelectedItem() == "Barbacoa")
        {
            tacosItem.setText("Barbacoa");
            Taco.setName("Barbacoa Taco");
            Taco.setPrice(2.5);
            subtotal=subtotal+Taco.getPrice();
        }
    }//GEN-LAST:event_tacosComboBoxActionPerformed

    /**************************************************************************
        Purpose: [Add to Cart Button] writes to Review Order Panel, while
                resetting the window
        Returns: None *********************************************************/
    private void tacosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tacosBtnActionPerformed
        String type = tacosItem.getText();
        String editStyle = tStyle.getSelectedItem().toString();
        
        //concatenates if user selects multiple toppings
        List<String> toppings = new ArrayList<String>(); 
        if(noTopping1.isSelected())
            toppings.add(" Cheese ");
        if(noTopping2.isSelected())
            toppings.add(" Cilantro ");
        if(noTopping3.isSelected())
            toppings.add(" Onions ");
        
        //appends to text area
        checkoutTextArea.append(type + " Tacos \n");         
        checkoutTextArea.append("  > Tortilla Style: "+ editStyle);
            for(int i=0; i < toppings.size();i++){
                checkoutTextArea.append("\n   > Pick it off:" + toppings.get(i));
            }
            
        runSubtotal.setText("Subtotal: \n $" + formatter.format(subtotal)); //label with running subtotal

        //the following resets the window
        drinksComboBox.setVisible(false);
        breakfastComboBox.setVisible(false);
        tacosComboBox.setVisible(false);
        noTopping1.setSelected(false);
        noTopping2.setSelected(false);
        noTopping3.setSelected(false);
        
        cardLayout.show(cardPanel, "homePanel");
    }//GEN-LAST:event_tacosBtnActionPerformed

    /**************************************************************************
        Purpose: [Pay Order Button] writes to a text file and calculates total
        *           bill
        Returns: None *********************************************************/
    private void payBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payBtnActionPerformed
        // TODO add your handling code here:
        //writes to a file
        
        bill.setSubtotal(subtotal);
        
        String printSubTotal = String.valueOf(subtotal);
        
        if(evt.getSource() == payBtn)
        {
            try 
            {
                PrintWriter out = new PrintWriter(new FileWriter("TestFile.txt"));
                checkoutTextArea.write(out);
                out.write("Subtotal: $"+ printSubTotal + "\n");
                out.write("Tax: $" +formatter.format(bill.taxcalculate()) + "\n");
                out.write("Tax: $" +formatter.format(bill.billcalculate()) + "\n");
                out.close();
                JOptionPane.showMessageDialog(this, "Successful Order.");

            } catch (IOException e1) {
                System.err.println("Error occurred");
                e1.printStackTrace();
            }
        }
    }//GEN-LAST:event_payBtnActionPerformed
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> bFirstTop;
    private javax.swing.JComboBox<String> bSecTop;
    private javax.swing.JComboBox<String> bStyle;
    private javax.swing.JButton bfBtn;
    private javax.swing.JComboBox<String> breakfastComboBox;
    private javax.swing.JLabel breakfastItem;
    private javax.swing.JLabel breakfastLbl;
    private javax.swing.JPanel breakfastPanel;
    private javax.swing.JPanel cardPanel;
    private javax.swing.JPanel checkoutPanel;
    private javax.swing.JTextArea checkoutTextArea;
    private javax.swing.JLabel drinkItem;
    private javax.swing.JLabel drinkLbl;
    private javax.swing.JButton drinksBtn;
    public javax.swing.JComboBox<String> drinksComboBox;
    private javax.swing.JPanel drinksPanel;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JCheckBox noTopping1;
    private javax.swing.JCheckBox noTopping2;
    private javax.swing.JCheckBox noTopping3;
    private javax.swing.JButton payBtn;
    private javax.swing.JLabel runSubtotal;
    private javax.swing.JComboBox<String> tStyle;
    private javax.swing.JButton tacosBtn;
    private javax.swing.JComboBox<String> tacosComboBox;
    private javax.swing.JLabel tacosItem;
    private javax.swing.JLabel tacosLbl;
    private javax.swing.JPanel tacosPanel;
    // End of variables declaration//GEN-END:variables
}
